[2024-08-29T16:34:21.079+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T16:34:21.103+0300] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tc4a_data_visualization.bq_zoom_data_load_csv manual__2024-08-29T13:13:27.663804+00:00 [queued]>
[2024-08-29T16:34:21.112+0300] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tc4a_data_visualization.bq_zoom_data_load_csv manual__2024-08-29T13:13:27.663804+00:00 [queued]>
[2024-08-29T16:34:21.112+0300] {taskinstance.py:2856} INFO - Starting attempt 6 of 6
[2024-08-29T16:34:21.128+0300] {taskinstance.py:2879} INFO - Executing <Task(GCSToBigQueryOperator): bq_zoom_data_load_csv> on 2024-08-29 13:13:27.663804+00:00
[2024-08-29T16:34:21.140+0300] {logging_mixin.py:190} WARNING - /home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=95851) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-29T16:34:21.141+0300] {standard_task_runner.py:72} INFO - Started process 95940 to run task
[2024-08-29T16:34:21.139+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tc4a_data_visualization', 'bq_zoom_data_load_csv', 'manual__2024-08-29T13:13:27.663804+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/postgres_setup.py', '--cfg-path', '/tmp/tmpdzc8d2_4']
[2024-08-29T16:34:21.142+0300] {standard_task_runner.py:105} INFO - Job 42: Subtask bq_zoom_data_load_csv
[2024-08-29T16:34:21.215+0300] {task_command.py:467} INFO - Running <TaskInstance: tc4a_data_visualization.bq_zoom_data_load_csv manual__2024-08-29T13:13:27.663804+00:00 [running]> on host sa
[2024-08-29T16:34:21.348+0300] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tc4a' AIRFLOW_CTX_DAG_ID='tc4a_data_visualization' AIRFLOW_CTX_TASK_ID='bq_zoom_data_load_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T13:13:27.663804+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-29T13:13:27.663804+00:00'
[2024-08-29T16:34:21.349+0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-29T16:34:21.400+0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-08-29T16:34:21.403+0300] {base.py:84} INFO - Retrieving connection 'gcp_conn'
[2024-08-29T16:34:21.404+0300] {gcs_to_bigquery.py:381} INFO - Using existing BigQuery table for storing data...
[2024-08-29T16:34:21.464+0300] {gcs_to_bigquery.py:385} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'visualization-app-404406', 'datasetId': 'tc4a', 'tableId': 'bq_zoomreports'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://tc4a-backet/zoom_reports_2024-08-29.json'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'id', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'event_name', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'email', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'profession', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'country', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'county', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'duration', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'phone_number', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'board_number', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'medical_number', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'email_consent', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'specialization', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'gender', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'created_at', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}, {'name': 'updated_at', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}]}, 'maxBadRecords': 100, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-08-29T16:34:21.465+0300] {bigquery.py:1702} INFO - Inserting job airflow_tc4a_data_visualization_bq_zoom_data_load_csv_2024_08_29T13_13_27_663804_00_00_9d8495d75966ee864cb01d0b10983121
[2024-08-29T16:34:25.401+0300] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 446, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://tc4a-backet/zoom_reports_2024-08-29.json; reason: notFound, message: Not found: URI gs://tc4a-backet/zoom_reports_2024-08-29.json
[2024-08-29T16:34:25.416+0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tc4a_data_visualization, task_id=bq_zoom_data_load_csv, run_id=manual__2024-08-29T13:13:27.663804+00:00, execution_date=20240829T131327, start_date=20240829T133421, end_date=20240829T133425
[2024-08-29T16:34:25.434+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-29T16:34:25.435+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task bq_zoom_data_load_csv (404 Not found: URI gs://tc4a-backet/zoom_reports_2024-08-29.json; reason: notFound, message: Not found: URI gs://tc4a-backet/zoom_reports_2024-08-29.json; 95940)
Traceback (most recent call last):
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 446, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://tc4a-backet/zoom_reports_2024-08-29.json; reason: notFound, message: Not found: URI gs://tc4a-backet/zoom_reports_2024-08-29.json
[2024-08-29T16:34:25.452+0300] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-29T16:34:25.468+0300] {local_task_job_runner.py:240} INFO - ::endgroup::
