[2024-08-29T14:21:30.626+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T14:21:30.642+0300] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_data_pipeline.fetch_data_from_postgres scheduled__2024-08-28T00:00:00+00:00 [queued]>
[2024-08-29T14:21:30.649+0300] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_data_pipeline.fetch_data_from_postgres scheduled__2024-08-28T00:00:00+00:00 [queued]>
[2024-08-29T14:21:30.649+0300] {taskinstance.py:2856} INFO - Starting attempt 6 of 7
[2024-08-29T14:21:30.660+0300] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): fetch_data_from_postgres> on 2024-08-28 00:00:00+00:00
[2024-08-29T14:21:30.666+0300] {logging_mixin.py:190} WARNING - /home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=52169) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-29T14:21:30.667+0300] {standard_task_runner.py:72} INFO - Started process 52208 to run task
[2024-08-29T14:21:30.666+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reports_data_pipeline', 'fetch_data_from_postgres', 'scheduled__2024-08-28T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpz6j9yuav']
[2024-08-29T14:21:30.668+0300] {standard_task_runner.py:105} INFO - Job 20: Subtask fetch_data_from_postgres
[2024-08-29T14:21:30.705+0300] {task_command.py:467} INFO - Running <TaskInstance: reports_data_pipeline.fetch_data_from_postgres scheduled__2024-08-28T00:00:00+00:00 [running]> on host sa
[2024-08-29T14:21:30.763+0300] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tc4a' AIRFLOW_CTX_DAG_ID='reports_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-08-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-28T00:00:00+00:00'
[2024-08-29T14:21:30.764+0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-29T14:21:30.781+0300] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-08-29T14:21:30.787+0300] {setup.py:36} INFO - Saved data to dags/zoom_report_20240828.csv
[2024-08-29T14:21:30.787+0300] {python.py:240} INFO - Done. Returned value was: None
[2024-08-29T14:21:30.794+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-29T14:21:30.795+0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=reports_data_pipeline, task_id=fetch_data_from_postgres, run_id=scheduled__2024-08-28T00:00:00+00:00, execution_date=20240828T000000, start_date=20240829T112130, end_date=20240829T112130
[2024-08-29T14:21:30.840+0300] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-29T14:21:30.860+0300] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-29T14:21:30.861+0300] {local_task_job_runner.py:240} INFO - ::endgroup::
