[2024-08-29T14:02:18.919+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T14:02:18.934+0300] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_data_pipeline.upload_data_to_gcs scheduled__2024-08-28T00:00:00+00:00 [queued]>
[2024-08-29T14:02:18.939+0300] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_data_pipeline.upload_data_to_gcs scheduled__2024-08-28T00:00:00+00:00 [queued]>
[2024-08-29T14:02:18.940+0300] {taskinstance.py:2856} INFO - Starting attempt 3 of 4
[2024-08-29T14:02:18.950+0300] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): upload_data_to_gcs> on 2024-08-28 00:00:00+00:00
[2024-08-29T14:02:18.957+0300] {logging_mixin.py:190} WARNING - /home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=39093) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-29T14:02:18.957+0300] {standard_task_runner.py:72} INFO - Started process 39190 to run task
[2024-08-29T14:02:18.957+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reports_data_pipeline', 'upload_data_to_gcs', 'scheduled__2024-08-28T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpy0jqgaz_']
[2024-08-29T14:02:18.958+0300] {standard_task_runner.py:105} INFO - Job 12: Subtask upload_data_to_gcs
[2024-08-29T14:02:18.999+0300] {task_command.py:467} INFO - Running <TaskInstance: reports_data_pipeline.upload_data_to_gcs scheduled__2024-08-28T00:00:00+00:00 [running]> on host sa
[2024-08-29T14:02:19.072+0300] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tc4a' AIRFLOW_CTX_DAG_ID='reports_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_data_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-08-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-28T00:00:00+00:00'
[2024-08-29T14:02:19.073+0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-29T14:02:19.093+0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-08-29T14:02:19.095+0300] {base.py:84} INFO - Retrieving connection 'gcp_conn'
[2024-08-29T14:02:19.096+0300] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/dags/setup.py", line 43, in upload_data_to_gcs
    gcs_hook.upload(bucket, destination_blob_name,filename=file_path)
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 528, in upload
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 363, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 335, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 411, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 257, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 315, in _get_credentials_using_key_path
    credentials = google.oauth2.service_account.Credentials.from_service_account_file(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/google/oauth2/service_account.py", line 259, in from_service_account_file
    info, signer = _service_account_info.from_filename(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/airflow/dags/gcp/service_account.json'
[2024-08-29T14:02:19.107+0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=reports_data_pipeline, task_id=upload_data_to_gcs, run_id=scheduled__2024-08-28T00:00:00+00:00, execution_date=20240828T000000, start_date=20240829T110218, end_date=20240829T110219
[2024-08-29T14:02:19.120+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-29T14:02:19.121+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task upload_data_to_gcs ([Errno 2] No such file or directory: '/airflow/dags/gcp/service_account.json'; 39190)
Traceback (most recent call last):
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/dags/setup.py", line 43, in upload_data_to_gcs
    gcs_hook.upload(bucket, destination_blob_name,filename=file_path)
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 528, in upload
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 363, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 335, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 411, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 257, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 315, in _get_credentials_using_key_path
    credentials = google.oauth2.service_account.Credentials.from_service_account_file(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/google/oauth2/service_account.py", line 259, in from_service_account_file
    info, signer = _service_account_info.from_filename(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/airflow/dags/gcp/service_account.json'
[2024-08-29T14:02:19.131+0300] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-29T14:02:19.149+0300] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-29T14:02:19.153+0300] {local_task_job_runner.py:240} INFO - ::endgroup::
